/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AlunoHistoricoRouteImport } from './routes/aluno.historico'
import { Route as AdminTreinosRouteImport } from './routes/admin.treinos'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AlunoHistoricoRoute = AlunoHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminTreinosRoute = AdminTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/aluno/historico': typeof AlunoHistoricoRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/aluno/historico': typeof AlunoHistoricoRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/aluno/historico': typeof AlunoHistoricoRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aluno'
    | '/login'
    | '/admin/alunos'
    | '/admin/treinos'
    | '/aluno/historico'
    | '/admin/'
    | '/aluno/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/alunos'
    | '/admin/treinos'
    | '/aluno/historico'
    | '/admin'
    | '/aluno'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aluno'
    | '/login'
    | '/admin/alunos'
    | '/admin/treinos'
    | '/aluno/historico'
    | '/admin/'
    | '/aluno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/aluno/historico': {
      id: '/aluno/historico'
      path: '/historico'
      fullPath: '/aluno/historico'
      preLoaderRoute: typeof AlunoHistoricoRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/treinos': {
      id: '/admin/treinos'
      path: '/treinos'
      fullPath: '/admin/treinos'
      preLoaderRoute: typeof AdminTreinosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminTreinosRoute: typeof AdminTreinosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminTreinosRoute: AdminTreinosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlunoRouteChildren {
  AlunoHistoricoRoute: typeof AlunoHistoricoRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoHistoricoRoute: AlunoHistoricoRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
