/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AlunoHistoricoRouteImport } from './routes/aluno.historico'
import { Route as AdminTreinosRouteImport } from './routes/admin.treinos'
import { Route as AdminPessoalRouteImport } from './routes/admin.pessoal'
import { Route as AdminPadraoRouteImport } from './routes/admin.padrao'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCheckinsRouteImport } from './routes/admin.checkins'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminAlunoIdRouteImport } from './routes/admin.aluno.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AlunoHistoricoRoute = AlunoHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminTreinosRoute = AdminTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPessoalRoute = AdminPessoalRouteImport.update({
  id: '/pessoal',
  path: '/pessoal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPadraoRoute = AdminPadraoRouteImport.update({
  id: '/padrao',
  path: '/padrao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckinsRoute = AdminCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunoIdRoute = AdminAlunoIdRouteImport.update({
  id: '/aluno/$id',
  path: '/aluno/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/checkins': typeof AdminCheckinsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/padrao': typeof AdminPadraoRoute
  '/admin/pessoal': typeof AdminPessoalRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/aluno/historico': typeof AlunoHistoricoRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/admin/aluno/$id': typeof AdminAlunoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/checkins': typeof AdminCheckinsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/padrao': typeof AdminPadraoRoute
  '/admin/pessoal': typeof AdminPessoalRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/aluno/historico': typeof AlunoHistoricoRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
  '/admin/aluno/$id': typeof AdminAlunoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/checkins': typeof AdminCheckinsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/padrao': typeof AdminPadraoRoute
  '/admin/pessoal': typeof AdminPessoalRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/aluno/historico': typeof AlunoHistoricoRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/admin/aluno/$id': typeof AdminAlunoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aluno'
    | '/login'
    | '/admin/alunos'
    | '/admin/checkins'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/padrao'
    | '/admin/pessoal'
    | '/admin/treinos'
    | '/aluno/historico'
    | '/admin/'
    | '/aluno/'
    | '/admin/aluno/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/alunos'
    | '/admin/checkins'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/padrao'
    | '/admin/pessoal'
    | '/admin/treinos'
    | '/aluno/historico'
    | '/admin'
    | '/aluno'
    | '/admin/aluno/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aluno'
    | '/login'
    | '/admin/alunos'
    | '/admin/checkins'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/padrao'
    | '/admin/pessoal'
    | '/admin/treinos'
    | '/aluno/historico'
    | '/admin/'
    | '/aluno/'
    | '/admin/aluno/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/aluno/historico': {
      id: '/aluno/historico'
      path: '/historico'
      fullPath: '/aluno/historico'
      preLoaderRoute: typeof AlunoHistoricoRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/treinos': {
      id: '/admin/treinos'
      path: '/treinos'
      fullPath: '/admin/treinos'
      preLoaderRoute: typeof AdminTreinosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pessoal': {
      id: '/admin/pessoal'
      path: '/pessoal'
      fullPath: '/admin/pessoal'
      preLoaderRoute: typeof AdminPessoalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/padrao': {
      id: '/admin/padrao'
      path: '/padrao'
      fullPath: '/admin/padrao'
      preLoaderRoute: typeof AdminPadraoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkins': {
      id: '/admin/checkins'
      path: '/checkins'
      fullPath: '/admin/checkins'
      preLoaderRoute: typeof AdminCheckinsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aluno/$id': {
      id: '/admin/aluno/$id'
      path: '/aluno/$id'
      fullPath: '/admin/aluno/$id'
      preLoaderRoute: typeof AdminAlunoIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminCheckinsRoute: typeof AdminCheckinsRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminPadraoRoute: typeof AdminPadraoRoute
  AdminPessoalRoute: typeof AdminPessoalRoute
  AdminTreinosRoute: typeof AdminTreinosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlunoIdRoute: typeof AdminAlunoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminCheckinsRoute: AdminCheckinsRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminPadraoRoute: AdminPadraoRoute,
  AdminPessoalRoute: AdminPessoalRoute,
  AdminTreinosRoute: AdminTreinosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlunoIdRoute: AdminAlunoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlunoRouteChildren {
  AlunoHistoricoRoute: typeof AlunoHistoricoRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoHistoricoRoute: AlunoHistoricoRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
